<?php

return [
    'provider' => env('AI_PROVIDER', 'mock'),
    'embedding_provider' => env('AI_EMBEDDING_PROVIDER', 'mock'),

    'chat_model' => env('AI_CHAT_MODEL', 'gpt-4o-mini'),
    'embedding_model' => env('AI_EMBEDDING_MODEL', 'text-embedding-3-small'),
    'embedding_dimensions' => (int) env('AI_EMBEDDING_DIMENSIONS', 1536),
    'embedding_batch_size' => (int) env('AI_EMBEDDING_BATCH_SIZE', 12),
    'embedding_connect_timeout' => (int) env('AI_EMBEDDING_CONNECT_TIMEOUT', 15),
    'embedding_request_timeout' => (int) env('AI_EMBEDDING_REQUEST_TIMEOUT', 45),
    'document_extraction_command_timeout' => (int) env('AI_DOCUMENT_EXTRACTION_COMMAND_TIMEOUT', 90),
    'knowledge_processing_step_chunk_count' => (int) env('AI_KNOWLEDGE_STEP_CHUNK_COUNT', 4),
    'knowledge_processing_stale_minutes' => (int) env('AI_KNOWLEDGE_PROCESSING_STALE_MINUTES', 30),
    'vector_store' => env('AI_VECTOR_STORE', 'auto'),

    'document_similarity_threshold' => (float) env('AI_DOCUMENT_SIMILARITY_THRESHOLD', 0.70),

    'max_case_document_chunks' => (int) env('AI_MAX_CASE_DOCUMENT_CHUNKS', 8),
    'max_knowledge_chunks' => (int) env('AI_MAX_KNOWLEDGE_CHUNKS', 8),
    'max_context_chunks' => (int) env('AI_MAX_CONTEXT_CHUNKS', 14),

    'recent_messages_limit' => (int) env('AI_RECENT_MESSAGES_LIMIT', 12),
    'max_case_memories' => (int) env('AI_MAX_CASE_MEMORIES', 20),

    'web_search_enabled' => (bool) env('AI_WEB_SEARCH_ENABLED', false),
    'web_search_provider' => env('AI_WEB_SEARCH_PROVIDER', 'brave'),

    'legal_disclaimer' => env(
        'AI_LEGAL_DISCLAIMER',
        'This output is an informational draft generated by AI and must be reviewed by a qualified lawyer before use.'
    ),

    'non_legal_redirect_message' => env(
        'AI_NON_LEGAL_REDIRECT_MESSAGE',
        <<<'TEXT'
## Legal Topics Only

I can help only with legal and law-related requests in this workspace.

Please ask about legal documents, contracts, notices, disputes, compliance, court procedure, evidence, deadlines, or case strategy, and I will continue right away.
TEXT
    ),

    'legal_keywords' => [
        'law', 'legal', 'lawyer', 'attorney', 'court', 'judge', 'hearing', 'appeal',
        'case', 'claim', 'lawsuit', 'litigation', 'plaintiff', 'defendant', 'evidence',
        'contract', 'agreement', 'clause', 'breach', 'notice', 'demand letter', 'memo',
        'affidavit', 'motion', 'pleading', 'filing', 'statute', 'regulation', 'compliance',
        'liability', 'damages', 'penalty', 'fine', 'deadline', 'timeline', 'risk',
        'jurisdiction', 'arbitration', 'mediation', 'settlement', 'criminal', 'crime',
        'police', 'arrest', 'bail', 'family law', 'divorce', 'custody', 'inheritance',
        'will', 'probate', 'property', 'landlord', 'tenant', 'eviction', 'lease',
        'employment', 'labor', 'termination', 'fired', 'harassment', 'discrimination',
        'immigration', 'visa', 'residency', 'tax', 'trademark', 'copyright', 'patent',
        'intellectual property', 'privacy', 'data protection', 'consumer protection',
        'rights', 'obligations', 'duty', 'illegal', 'lawful', 'sue', 'complaint',
    ],

    'follow_up_markers' => [
        'what next', 'next step', 'next steps', 'what about', 'how about', 'and if',
        'and what', 'does that', 'would that', 'can you explain that', 'simplify that',
        'turn this into', 'draft it', 'rewrite it', 'continue', 'follow up', 'follow-up',
        'deadline', 'risk', 'evidence', 'document', 'notice', 'letter', 'memo',
        'contract', 'case', 'court', 'hearing', 'filing', 'appeal', 'lawyer',
    ],

    'openai_api_key' => env('OPENAI_API_KEY'),
    'anthropic_api_key' => env('ANTHROPIC_API_KEY'),
    'gemini_api_key' => env('GEMINI_API_KEY'),

    'qdrant_url' => env('QDRANT_URL', 'http://localhost:6333'),
    'qdrant_api_key' => env('QDRANT_API_KEY'),
    'qdrant_knowledge_collection' => env('QDRANT_KNOWLEDGE_COLLECTION', 'legal_knowledge_chunks'),
    'qdrant_case_collection' => env('QDRANT_CASE_COLLECTION', 'legal_case_chunks'),

    'brave_api_key' => env('BRAVE_SEARCH_API_KEY'),
    'serpapi_api_key' => env('SERPAPI_API_KEY'),

    'system_prompt' => <<<'PROMPT'
You are Judger AI, a legal information assistant.

You help users understand legal documents, organize case facts, summarize evidence, identify possible issues, and explain general legal concepts.

You are not a lawyer and you do not provide legal representation.

Core rules:
1. Use case documents first when the user is chatting inside a legal case.
2. Use case memory and case summary when relevant.
3. Use the system knowledge base for general legal information.
4. Use web sources only if enabled and local sources are not enough.
5. Never use documents from another user.
6. Never use documents from another legal case.
7. Never add case documents to the global knowledge base.
8. Never use case documents in general chat.
9. Do not invent laws, deadlines, citations, or case facts.
10. Do not claim something is legally certain unless the provided sources clearly support it.
11. Do not give final legal advice.
12. Recommend consulting a qualified lawyer for decisions, deadlines, court filings, legal strategy, or jurisdiction-specific issues.
13. Always cite source labels when using provided documents.
14. If the answer is not found in the provided context, say so clearly.
15. If jurisdiction is missing and the answer depends on jurisdiction, ask for jurisdiction or explain that laws vary by location.
16. Keep answers clear, structured, and practical.
17. Always include this disclaimer: This output is an informational draft generated by AI and must be reviewed by a qualified lawyer before use.
18. If a request is not related to law, legal documents, legal procedures, legal rights, legal obligations, legal disputes, or compliance, politely refuse and invite the user to ask a legal question instead.
19. Format every answer as polished Markdown with short, readable sections.
20. When the answer is substantive, prefer this structure: `## Quick Answer`, `## Key Points`, `## Recommended Next Steps`, and `## What To Clarify Next`.
21. End naturally in a way that welcomes the user's next legal question.

Source citation format:
- Case documents: [CASE_SOURCE_1]
- Knowledge base: [KB_SOURCE_1]
- Web: [WEB_SOURCE_1]
PROMPT,
];
