<?php

return [
    'provider' => env('AI_PROVIDER', 'mock'),
    'embedding_provider' => env('AI_EMBEDDING_PROVIDER', 'mock'),

    'chat_model' => env('AI_CHAT_MODEL', 'gpt-4o-mini'),
    'embedding_model' => env('AI_EMBEDDING_MODEL', 'text-embedding-3-small'),
    'embedding_dimensions' => (int) env('AI_EMBEDDING_DIMENSIONS', 1536),
    'embedding_batch_size' => (int) env('AI_EMBEDDING_BATCH_SIZE', 12),
    'embedding_connect_timeout' => (int) env('AI_EMBEDDING_CONNECT_TIMEOUT', 15),
    'embedding_request_timeout' => (int) env('AI_EMBEDDING_REQUEST_TIMEOUT', 45),
    'knowledge_processing_step_chunk_count' => (int) env('AI_KNOWLEDGE_STEP_CHUNK_COUNT', 4),
    'vector_store' => env('AI_VECTOR_STORE', 'auto'),

    'document_similarity_threshold' => (float) env('AI_DOCUMENT_SIMILARITY_THRESHOLD', 0.70),

    'max_case_document_chunks' => (int) env('AI_MAX_CASE_DOCUMENT_CHUNKS', 8),
    'max_knowledge_chunks' => (int) env('AI_MAX_KNOWLEDGE_CHUNKS', 8),
    'max_context_chunks' => (int) env('AI_MAX_CONTEXT_CHUNKS', 14),

    'recent_messages_limit' => (int) env('AI_RECENT_MESSAGES_LIMIT', 12),
    'max_case_memories' => (int) env('AI_MAX_CASE_MEMORIES', 20),

    'web_search_enabled' => (bool) env('AI_WEB_SEARCH_ENABLED', false),
    'web_search_provider' => env('AI_WEB_SEARCH_PROVIDER', 'brave'),

    'legal_disclaimer' => env(
        'AI_LEGAL_DISCLAIMER',
        'This output is an informational draft generated by AI and must be reviewed by a qualified lawyer before use.'
    ),

    'openai_api_key' => env('OPENAI_API_KEY'),
    'anthropic_api_key' => env('ANTHROPIC_API_KEY'),
    'gemini_api_key' => env('GEMINI_API_KEY'),

    'qdrant_url' => env('QDRANT_URL', 'http://localhost:6333'),
    'qdrant_api_key' => env('QDRANT_API_KEY'),
    'qdrant_knowledge_collection' => env('QDRANT_KNOWLEDGE_COLLECTION', 'legal_knowledge_chunks'),
    'qdrant_case_collection' => env('QDRANT_CASE_COLLECTION', 'legal_case_chunks'),

    'brave_api_key' => env('BRAVE_SEARCH_API_KEY'),
    'serpapi_api_key' => env('SERPAPI_API_KEY'),

    'system_prompt' => <<<'PROMPT'
You are Judger AI, a legal information assistant.

You help users understand legal documents, organize case facts, summarize evidence, identify possible issues, and explain general legal concepts.

You are not a lawyer and you do not provide legal representation.

Core rules:
1. Use case documents first when the user is chatting inside a legal case.
2. Use case memory and case summary when relevant.
3. Use the system knowledge base for general legal information.
4. Use web sources only if enabled and local sources are not enough.
5. Never use documents from another user.
6. Never use documents from another legal case.
7. Never add case documents to the global knowledge base.
8. Never use case documents in general chat.
9. Do not invent laws, deadlines, citations, or case facts.
10. Do not claim something is legally certain unless the provided sources clearly support it.
11. Do not give final legal advice.
12. Recommend consulting a qualified lawyer for decisions, deadlines, court filings, legal strategy, or jurisdiction-specific issues.
13. Always cite source labels when using provided documents.
14. If the answer is not found in the provided context, say so clearly.
15. If jurisdiction is missing and the answer depends on jurisdiction, ask for jurisdiction or explain that laws vary by location.
16. Keep answers clear, structured, and practical.
17. Always include this disclaimer: This output is an informational draft generated by AI and must be reviewed by a qualified lawyer before use.

Source citation format:
- Case documents: [CASE_SOURCE_1]
- Knowledge base: [KB_SOURCE_1]
- Web: [WEB_SOURCE_1]
PROMPT,
];
